##  -------------------------------------------------------------- ##
##  APPLICATION SETTINGS
##  ATTENTION: This file is AUTOGENERATED from $0 template
##  -------------------------------------------------------------- ##

APP_ENV=${NODE_ENV}
APP_DEBUG=$("dev" eq "${APP_ENV}" || "development" eq "${APP_ENV}")

APP_NAME="${APP_NAME}"
APP_TITLE="${APP_TITLE}"
APP_DOMAIN="${APP_NAME}.${APP_ENV}"

// WWW_USER="www-data"
// WORKDIR="/var/www/"
WEB_USER="www-data"
WEB_HOME="/var/www/"


GIT_REPO="https://github.com/PrestaShop/PrestaShop.git"
GIT_DIR="PrestaShop.git"

##  -------------------------------------------------------------- ##
##  ENGINE OPTIONS
##  -------------------------------------------------------------- ##

DIR_ROOT="/var/www/html/${APP_NAME}"
DIR_WEB="webroot"
DIR_BACK="/opt/backup"

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

#REDIS_HOST=127.0.0.1
#REDIS_PASSWORD=null
#REDIS_PORT=6379

#MAIL_DRIVER=smtp
#MAIL_HOST=mailtrap.io
#MAIL_PORT=2525
#MAIL_USERNAME=null
#MAIL_PASSWORD=null
#MAIL_ENCRYPTION=null

##  -------------------------------------------------------------- ##
##  MYSQL DOCKER IMAGE SETTINGS
##  -------------------------------------------------------------- ##

MYSQL_ROOT_PW=$(date +"%N" | md5sum | cut -b1-32)
MYSQL_TAG=${DB_ENGINE_TAG}
MYSQL_USER="mysql"

##  -------------------------------------------------------------- ##
##  DATABASE SETTINGS
##  -------------------------------------------------------------- ##

DB_HOST="localhost"
DB_PORT=3306
DB_NAME="${APP_NAME}_db"
DB_USER="${APP_NAME}_user"
DB_PASS="$(date +"%N" | md5sum | cut -b1-32)"
