# Only use spaces to indent .yml configuration.
# -----
# Custom docker image from Docker Hub as build environment.
# image: docker-image:tag

image: php:5.6-apache

pipelines:
  default:
    - step:
        script:
          - printf "This script runs on all branches that don't have any specific pipeline assigned in 'branches'.\n"
          - mkdir -p /srv >/dev/null &2>1
          - cp ./setup.rc /srv/*.*;
          - source /srv/setup.rc;
          - printf "APP_NAME = [${APP_NAME}]\n";
          - lscpu
          - ls /home
          - printf "Everything is awesome!\n"
  branches:
    master:
      - step:
          image: tbaltrushaitis/gsmc-public:latest
          script:
            - printf "This script runs only on commit to the MASTER branch.\n";
            - printf "Here are some system info:\n";
            - uname -a
            - free -m
            - df -H
            - printf "Processing operations ... \n";
            - mkdir -p /data/mongodb &> /dev/null &2>1;
            - mkdir -p /data/configdb &> /dev/null &2>1;
            - mkdir -p /srv &> /dev/null &2>1;
            - chmod 775 /srv;
            - cd /srv;
            - pwd;
            - printf "/SRV:\n";
            - ls -als;
            - printf "/HOME:\n";
            - ls -als /home/;
            # - cp ./*.rc /srv/*.*;
            # - cp ./*.sh /srv/*.*;
            # - chmod +x /srv/*.sh;
            # - . /srv/setup.sh;
            - printf "APP_NAME = [${APP_NAME}]\n";
            - printf "MYSQL_TAG = [${DB_ENGINE_TAG}]\n";
            - printf "\n\n\n[INFO] Master branch onpush build finished!\n";
    engine:
      - step:
          image: tbaltrushaitis/gsmc:latest
          script:
            - printf "This script runs only on commit to branch with <engine> label."
    notify:
      - step:
          script:
            - docker run hello-world
